server:
  port: 8001

spring:
  profiles:
    active:
    - dev 
---
spring:
  profiles: dev     #开发环境
  application: 
    name: springcloud-config-sanyueshiqi-dev
---
spring: 
  profiles: test    #测试环境
  application:
    name: springcloud-config-sanyueshiqi-test 